# Generated by Django 4.0.5 on 2022-08-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_income_options_alter_outcome_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
