# Generated by Django 4.0.5 on 2022-09-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_outcome_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='income',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', '0')), name='income_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='outcome',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', '0')), name='outcome_value_non_negative'),
        ),
    ]
