# Generated by Django 4.0.5 on 2022-09-10 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_income_income_value_non_negative_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='income',
            name='income_value_non_negative',
        ),
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
