# Generated by Django 4.0.5 on 2022-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_remove_income_income_value_non_negative'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='income',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', '0')), name='income_value_non_negative'),
        ),
    ]
