# Generated by Django 4.0.5 on 2022-10-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_alter_income_balance_alter_outcome_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.balance'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.balance'),
        ),
    ]
